services:
  train-producer:
    build: .
    image: train-traffic-produce:${VERSION:-latest}
    container_name: train-producer
    environment:
      BOOTSTRAP: kafka:29092
      PRIMARY_KEY: ${PRIMARY_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - server_default
    restart: unless-stopped
    stop_grace_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  server_default:
    external: true
